import { FilmData } from '../types/film';

const enum Genre {
  Musical = 'Musical',
  Western = 'Western',
  Drama = 'Drama',
  Comedy = 'Comedy',
  Cartoon = 'Cartoon',
  Mystery = 'Mystery',
}

const mokFilmList: FilmData[] = [
  {
    id: '12344',
    title: 'The Grand Budapest Hotel',
    background: 'img/bg-the-grand-budapest-hotel.jpg',
    poster: 'img/the-grand-budapest-hotel-poster.jpg',
    genre: Genre.Comedy,
    released: 2014,
    runTime: '1h 39m',
    director: 'Wes Anderson',
    starring: [
      'Bill Murray',
      'Edward Norton',
      'Jude Law',
      'Willem Dafoe',
      'Saoirse Ronan',
      'Tony Revoloru',
      'Tilda Swinton',
      'Tom Wilkinson',
      'Owen Wilkinson',
      'Adrien Brody',
      'Ralph Fiennes',
      'Jeff Goldblum',
    ],
    description:
      `In the 1930s, the Grand Budapest Hotel is a popular European ski
    resort, presided over by concierge Gustave H. (Ralph Fiennes). Zero, a
    junior lobby boy, becomes Gustave&apos;s friend and protege.`,
    rating: {
      score: '8,9',
      level: 'Very good',
      count: '240 ratings',
    },
    link: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
    trailer: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
  },
  {
    id: '12345',
    title: 'Fantastic Beasts: The Crimes of Grindelwald',
    background: 'img/fantastic-beasts-the-crimes-of-grindelwald.jpg',
    poster: 'img/the-grand-budapest-hotel-poster.jpg',
    genre: Genre.Mystery,
    released: 2007,
    runTime: '1h 59m',
    director: 'Anthony Mann',
    starring: [
      'Bill Murray',
      'Edward Norton',
      'Jude Law',
      'Willem Dafoe',
      'Saoirse Ronan',
      'Tony Revoloru',
      'Tilda Swinton',
      'Tom Wilkinson',
      'Owen Wilkinson',
      'Adrien Brody',
      'Ralph Fiennes',
      'Jeff Goldblum',
    ],
    description: 'In the 1930s, the Grand Budapest Hotel is a popular European ski resort...',
    rating: {
      score: '8,9',
      level: 'Bad',
      count: '240 ratings',
    },
    link: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
    trailer: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
  },
  {
    id: '12346',
    title: 'Bohemian Rhapsody',
    background: 'img/bohemian-rhapsody.jpg',
    poster: 'img/the-grand-budapest-hotel-poster.jpg',
    genre: Genre.Musical,
    released: 2008,
    runTime: '1h 20m',
    director: 'Martin Scorsese',
    starring: ['Robert De Niro', 'Dan Duryea', 'Jude Law', 'Katharine Hepburn'],
    description: 'In the 1930s, the Grand Budapest Hotel is a popular European ski resort 2',
    rating: {
      score: '6,9',
      level: 'Normal',
      count: '160 ratings',
    },
    link: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
    trailer: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
  },
  {
    id: '12347',
    title: 'Macbeth',
    background: 'img/macbeth.jpg',
    poster: 'img/the-grand-budapest-hotel-poster.jpg',
    genre: Genre.Drama,
    released: 2009,
    runTime: '1h 30m',
    director: 'Steven Spielberg',
    starring: ['Jack Nicholson', 'Daniel Day-Lewis', 'Mary Beth Hughes', 'Clark Gable'],
    description: 'In the 1930s, the Grand Budapest Hotel is a popular European ski resort 3',
    rating: {
      score: '4,3',
      level: 'Good',
      count: '240 ratings',
    },
    link: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
    trailer: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
  },
  {
    id: '12348',
    title: 'Aviator',
    background: 'img/aviator.jpg',
    poster: 'img/the-grand-budapest-hotel-poster.jpg',
    genre: Genre.Western,
    released: 2010,
    runTime: '1h 40m',
    director: 'George Lucas',
    starring: ['Marlon Brando', 'Sidney Poitier', 'Jack Nicholson', 'Humphrey Bogart'],
    description: 'In the 1930s, the Grand Budapest Hotel is a popular European ski resort 4',
    rating: {
      score: '8,0',
      level: 'Awesome',
      count: '220 ratings',
    },
    link: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
    trailer: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
  },
  {
    id: '12349',
    title: 'We need to talk about Kevin',
    background: 'img/we-need-to-talk-about-kevin.jpg',
    poster: 'img/the-grand-budapest-hotel-poster.jpg',
    genre: Genre.Drama,
    released: 2021,
    runTime: '1h 45m',
    director: 'James Cameron',
    starring: ['Denzel Washington', 'Clark Gable', 'Sidney Poitier', 'Tom Hanks'],
    description: 'In the 1930s, the Grand Budapest Hotel is a popular European ski resort 5',
    rating: {
      score: '10,0',
      level: 'Very good',
      count: '99 ratings',
    },
    link: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
    trailer: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
  },
  {
    id: '12310',
    title: 'What We Do in the Shadows',
    background: 'img/what-we-do-in-the-shadows.jpg',
    poster: 'img/the-grand-budapest-hotel-poster.jpg',
    genre: Genre.Mystery,
    released: 2019,
    runTime: '2h 05m',
    director: 'Quentin Tarantino',
    starring: ['Katharine Hepburn', 'Ingrid Bergman', 'Jude Law', 'Willem Dafoe'],
    description: 'In the 1930s, the Grand Budapest Hotel is a popular European ski resort 6',
    rating: {
      score: '7,1',
      level: 'Good',
      count: '210 ratings',
    },
    link: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
    trailer: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
  },
  {
    id: '12311',
    title: 'Revenant',
    background: 'img/revenant.jpg',
    poster: 'img/the-grand-budapest-hotel-poster.jpg',
    genre: Genre.Comedy,
    released: 2020,
    runTime: '1h 25m',
    director: 'David Fincher',
    starring: ['Humphrey Bogart', 'Tom Hanks', 'Jude Law', 'Erich von Stroheim'],
    description: 'In the 1930s, the Grand Budapest Hotel is a popular European ski resort 7',
    rating: {
      score: '4,3',
      level: 'Normal',
      count: '80 ratings',
    },
    link: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
    trailer: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
  },
  {
    id: '12312',
    title: 'Johnny English',
    background: 'img/johnny-english.jpg',
    poster: 'img/the-grand-budapest-hotel-poster.jpg',
    genre: Genre.Comedy,
    released: 2021,
    runTime: '1h 45m',
    director: 'Woody Allen',
    starring: ['Erich von Stroheim', 'Edward Norton', 'Mary Beth Hughes', 'Willem Dafoe'],
    description: 'In the 1930s, the Grand Budapest Hotel is a popular European ski resort 8',
    rating: {
      score: '5,6',
      level: 'Bad',
      count: '100 ratings',
    },
    link: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
    trailer: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
  },
];

export { mokFilmList };
